services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    ports:
      - "81:80"
      - "444:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../traefik/tls.toml:/etc/traefik/dynamic/tls.toml:ro
      - ../certs:/certs:ro
      - traefik-letsencrypt:/letsencrypt
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - processed_data:/app/data/outputs
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - OUTPUT_PATH=/app/data/outputs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app-secure.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.docker.network=docker_app-network"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  processed_data:
  traefik-letsencrypt: